
run_string: test_string.cpp bloom_filter.hpp
	@g++ test_string.cpp bloom_filter.hpp
	@./a.out $(TEST_FILE) $(BIT_COUNT) $(EXPECTED_INSERT)

run_int: test_int.cpp bloom_filter.hpp
	@g++ test_int.cpp bloom_filter.hpp
	@./a.out $(TEST_FILE) $(BIT_COUNT) $(EXPECTED_INSERT)

run_double: test_double.cpp bloom_filter.hpp
	@g++ test_double.cpp bloom_filter.hpp
	@./a.out $(TEST_FILE) $(BIT_COUNT) $(EXPECTED_INSERT)
